site_name: snotelpy
site_description: A Python package for accessing USDA SNOTEL snowpack data
repo_url: https://github.com/tavo7876/snotelpy

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_source: false
            show_root_heading: false

nav:
  - Home: index.md
  - Contributing: CONTRIBUTORS.md
  - API Reference:
    - Fetch: api/fetch.md
    - Basin: api/basin.md
    - Plot: api/plot.md